# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/46DF-34DF";
      fsType = "vfat";
    };

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
      options=[ "nofail" ];
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
      options=[ "nofail" ];
    };

  # fileSystems."/tank" =
  #   { device = "tank";
  #     fsType = "zfs";
  #     options=[ "nofail" ];
  #   };
  # fileSystems."/tank/house-scraper" =
  #   { device = "tank/house-scraper";
  #     fsType = "zfs";
  #     options=[ "nofail" ];
  #   };
  # fileSystems."/tank/ml" =
  #   { device = "tank/ml";
  #     fsType = "zfs";
  #     options=[ "nofail" ];
  #   };
  # fileSystems."/tank/open-sourdough" =
  #   { device = "tank/open-sourdough";
  #     fsType = "zfs";
  #     options=[ "nofail" ];
    # };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  hardware.bluetooth.enable = true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
